Add quarkus templates
contract-first-idp/developer-charts pull request #7
Opened 2024-09-19 17:31 UTC by Croway

2024-09-19 18:39 UTC, davgordo requested changes
can we try with the Quarkus builder image from Red Hat?

2024-09-19 18:39 UTC, davgordo commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +      value: 'andyhan/quarkus-mandrel-maven:jdk-21'
https://catalog.redhat.com/software/containers/quarkus/mandrel-for-jdk-21-rhel8/65dc6668aba78e5ae5961f80

2024-09-19 18:39 UTC, davgordo commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +        value: 'andyhan/quarkus-mandrel-maven:jdk-21'
https://catalog.redhat.com/software/containers/quarkus/mandrel-for-jdk-21-rhel8/65dc6668aba78e5ae5961f80

2024-09-20 03:40 UTC, svkcemk approved these changes
Great work @Croway

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +    runAfter: ["clone"]
Why is a json-style array used here instead of a more yaml-natural array?

```
runAfter: ["clone"]
```
vs
```
runAfter:
  - clone
```

There are several other locations through this pipeline that do this, too.

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +  {{- if or (eq .Values.deployment "jvm") (eq .Values.deployment "legacy-jar") }}
If deployment is set to `legacy-jar`, this pipeline won't work. The Dockerfile that will be built with legacy-jar expects a different style of packaging from Quarkus, and I don't see any modification made to change the JAR style that Quarkus builds.

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +      value: 'andyhan/quarkus-mandrel-maven:jdk-21'
I don't think that image you've linked will work instead of the andyhan one listed in the source here, @davgordo . The difference between the official Red Hat image and the andyhan-provided image is an installation of Maven. This pipeline appears to be intended for building Java code (using Maven), instrumenting with Quarkus (through Maven plugin), and compile into native (through Quarkus maven plugin calling Mandrel). The andyhan image should facilitate all of those. Note that the RH image is generally used by Quarkus maven plugin to perform only the native compilation part on systems that don't have mandrel or graalvm installed directly.

Personally, I'd go a different way with building to native in a pipeline, but... This probably still works.

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +    {{- if eq .Values.deployment "native" }}
Is there a reason to use completely separate if blocks? Why not do something like the following?
```
{{ else if eq .Values.deployment "native" }}
```

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/Chart.yaml
> +# pipeline. Library charts do not define any templates and therefore cannot be deployed.
Is all this boilerplate comment across this file relevant to this chart?

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-pipeline/Chart.yaml
> +name: helm
Perhaps this chart could use a better name...

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-application/Chart.yaml
> +name: helm
Perhaps this chart could use a better name...

2024-09-20 05:16 UTC, rmgrimm commented on quarkus-application/Chart.yaml
> +# It is recommended to use it with quotes.
It seems like there's an awful lot of boilerplate comment here that isn't relevant.

2024-09-20 07:39 UTC, Croway commented on quarkus-pipeline/templates/maven-pipeline.yaml
> +      value: 'andyhan/quarkus-mandrel-maven:jdk-21'
Hi @rmgrimm thanks for your review, I have similar feelings regarding this pipeline, but the thing is that I couldn't find any best practice from the quarkus team on how to build native applications on tekton, as far as I understand quarkus team offers two main strategies to build native image, using graalvm/mandrel, or dedicated images, the latter cannot be used as is on tekton (docker in docker?), that's why I used _quarkus-mandrel-maven_.

The pipeline works as expected as is, I wanted to keep it similar to the JVM one, but I am open to other building strategies.

2024-09-20 12:06 UTC, merged